import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { AuthProvider } from "@/app/_components/auth/AuthProvider";
import { ThemeProvider } from "next-themes";
import { I18nProvider } from "@/lib/i18n-client";

export const metadata: Metadata = {
  title: "Smart-Shelf",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.png", type: "image/png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geist.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="bg-background text-foreground font-sans antialiased">
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <I18nProvider>
            <AuthProvider>
              <TRPCReactProvider>{children}</TRPCReactProvider>
            </AuthProvider>
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
